services:
  app:
    image: ${APP_IMAGE}:${APP_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - env/app.env
    depends_on:
      - model-service
    restart: on-failure:3
  model-service:
    image: ${MODEL_SERVICE_IMAGE}:${MODEL_SERVICE_VERSION}
    volumes:
      - ./model-cache:/app/model-cache/
      - ./cv-cache:/app/cv-cache/
    env_file:
      - env/model_service.env
    restart: on-failure:3