apiVersion: v1
data:
  CV_CACHE_DIR: ./cv-cache
  CV_URL: https://github.com/remla25-team5/model-training/releases/download/{MODEL_VERSION}/c1_BoW_Sentiment_Model.pkl
  MODEL_CACHE_DIR: ./model-cache
  MODEL_SERVICE_HOST: localhost
  MODEL_SERVICE_PORT: "5000"
  MODEL_URL: https://github.com/remla25-team5/model-training/releases/download/{MODEL_VERSION}/c2_Classifier_Sentiment_Model.joblib
  MODEL_VERSION: 0.0.1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: model-service-model-service-env
  name: model-service-env
