apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: model-service
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: model-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: model-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: model-service-env
          image: ghcr.io/remla25-team5/model-service:latest
          name: model-service
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /app/model-cache
              name: model-service-claim1
            - mountPath: /app/cv-cache
              name: model-service-claim1
      restartPolicy: Always
      volumes:
        - name: model-service-claim0
          persistentVolumeClaim:
            claimName: model-service-claim0
        - name: model-service-claim1
          persistentVolumeClaim:
            claimName: model-service-claim1
