{
 "title": "Sentiment Analysis Dashboard",
 "description": "A dashboard containing important metric from the sentiment analysis application.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query_interval",
    "label": "Query Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "avg_interval",
    "label": "Average Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of submissions received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "total_submissions_total{sentiment=\"false\"}",
     "legendFormat": "Sentiment: {{sentiment}}"
    },
    {
     "expr": "total_submissions_total{sentiment=\"true\"}",
     "legendFormat": "Sentiment: {{sentiment}}"
    }
   ]
  },
  {
   "title": "Number of active submissions not yet verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "active_submissions{sentiment=\"true\"}",
     "legendFormat": "Sentiment: {{sentiment}}"
    },
    {
     "expr": "active_submissions{sentiment=\"false\"}",
     "legendFormat": "Sentiment: {{sentiment}}"
    }
   ]
  },
  {
   "title": "Rate of total number of submissions received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(total_submissions_total{sentiment=\"false\"}[${query_interval}])",
     "legendFormat": "Sentiment: {{sentiment}}"
    },
    {
     "expr": "rate(total_submissions_total{sentiment=\"true\"}[$__rate_interval])",
     "legendFormat": "Sentiment: {{sentiment}}"
    }
   ]
  },
  {
   "title": "Average number of active submissions not yet verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(active_submissions{sentiment=\"true\"}[${avg_interval}])",
     "legendFormat": "Sentiment: {{sentiment}}"
    },
    {
     "expr": "avg_over_time(active_submissions{sentiment=\"false\"}[${avg_interval}])",
     "legendFormat": "Sentiment: {{sentiment}}"
    }
   ]
  },
  {
   "title": "Count sentiment and verified combinations over time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "submission_verification_delay_seconds_count{sentiment=\"true\", verified=\"True\"}",
     "legendFormat": "Sent: {{sentiment}} / Ver: {{verified}}"
    },
    {
     "expr": "submission_verification_delay_seconds_count{sentiment=\"true\", verified=\"False\"}",
     "legendFormat": "Sent: {{sentiment}} / Ver: {{verified}}"
    },
    {
     "expr": "submission_verification_delay_seconds_count{sentiment=\"false\", verified=\"True\"}",
     "legendFormat": "Sent: {{sentiment}} / Ver: {{verified}}"
    },
    {
     "expr": "submission_verification_delay_seconds_count{sentiment=\"false\", verified=\"False\"}",
     "legendFormat": "Sent: {{sentiment}} / Ver: {{verified}}"
    }
   ]
  },
  {
   "title": "Verification Error Rate Per Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "verification_error_rate_last_week{pod=~\".*-v1-.*\"}\r\n",
     "legendFormat": "Version: V1"
    },
    {
     "expr": "verification_error_rate_last_week{pod=~\".*-v2-.*\"}",
     "legendFormat": "Version: V2"
    }
   ]
  }
 ]
}