apiVersion: v1
data:
  APP_SERVICE_HOST: 0.0.0.0
  APP_SERVICE_PORT: "8080"
  MODEL_SERVICE_HOST: model-service
  MODEL_SERVICE_PORT: "5000"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: app-app-env
  name: app-env
