replica_count: 1

app:
  image: ghcr.io/remla25-team5/app
  tag: latest
  port: 8080
  tagv2: latest

modelService:
  image: ghcr.io/remla25-team5/model-service
  tag: latest
  port: 5000
  tagv2: latest
  
persistentVolumeSize: 100Mi

monitoring:
  enabled: false
  scrapeInterval: 15s

gmailEmail: "@gmail.com"
emailPassword: value

grafana:
  ingress:
    host: grafana.local
    servicePort: 80
