replica_count: 1

app:
  image: ghcr.io/remla25-team5/app
  tag: latest
  port: 8080

modelService:
  image: ghcr.io/remla25-team5/model-service
  tag: latest
  port: 5000
  
persistentVolumeSize: 100Mi

monitoring:
  enabled: false
  scrapeInterval: 15s
