{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-am-config
  labels:
    release: {{ .Release.Name }}
spec:
  route:
    receiver: 'gmail-notifications'
  receivers:
  - name: 'gmail-notifications'
    emailConfigs:
    - to: "{{ .Values.gmailEmail }}"
      from: "{{ .Values.gmailEmail }}"
      smarthost: smtp.gmail.com:587
      authUsername: "{{ .Values.gmailEmail }}"
      authPassword:
        name: gmail-smtp-credentials
        key: appPassword
      authIdentity: "{{ .Values.gmailEmail }}"
      sendResolved: true
{{- end }}