apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-env
data:
  APP_SERVICE_HOST: {{ .Values.app.env.APP_SERVICE_HOST }}
  APP_SERVICE_PORT: {{ .Values.app.env.APP_SERVICE_PORT | quote }}
  MODEL_SERVICE_HOST: {{ .Values.app.env.MODEL_SERVICE_HOST }}
  MODEL_SERVICE_PORT: {{ .Values.app.env.MODEL_SERVICE_PORT | quote }}