apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: app
