apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: app
      {{- include "sentiment-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: app
        {{- include "sentiment-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-app-env
            - secretRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-app-secret
          env:
            - name: MODEL_SERVICE_HOST
              value: "{{ .Values.modelService.serviceName }}"
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared
      volumes:
        - name: shared-data
          hostPath:
            path: /mnt/shared