{{- if .Values.istioEnabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: { name: {{ include "sentiment-app-chart.fullname" . }}-virtualservice }
spec:
    gateways: [ {{ include "sentiment-app-chart.fullname" . }}-gateway ]
    hosts: [ {{ printf "%s%s" .Release.Name .Values.app.ingress.host | quote }} ]
    http:
    - match:
        - headers:
            x-experiment:
              exact: "true"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ include "sentiment-app-chart.fullname" . }}-app
            subset: v2
          weight: 100
    - match:
        - headers:
            x-experiment:
              exact: "false"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ include "sentiment-app-chart.fullname" . }}-app
            subset: v1
          weight: 100
    - match:
        - headers: 
            cookie: 
              regex: ".*app-version-preference=v1.*"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ include "sentiment-app-chart.fullname" . }}-app
            subset: v1
          weight: 100

    - match:
        - headers:
            cookie:
              regex: ".*app-version-preference=v2.*"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ include "sentiment-app-chart.fullname" . }}-app
            subset: v2
          weight: 100
    - match:
        - uri: { prefix: / }
      route:
      - destination: { host: {{ include "sentiment-app-chart.fullname" . }}-app, subset: v1 }
        weight: 90
      - destination: { host: {{ include "sentiment-app-chart.fullname" . }}-app, subset: v2 }
        weight: 10
      name: api
{{- end }}