apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "sentiment-app-chart.fullname" . }}-app
    {{- include "sentiment-app-chart.selectorLabels" . | nindent 4 }}
