apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app-env
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
data:
  APP_SERVICE_HOST: "0.0.0.0"
  APP_SERVICE_PORT: "8080"
  MODEL_SERVICE_HOST: "http://{{ include "sentiment-app-chart.fullname" . }}-model"
  MODEL_SERVICE_PORT: "5000"