apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: app
