{{- if .Values.istioEnabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: {{ include "sentiment-app-chart.fullname" . }}-app-dr }
spec:
  host: {{ include "sentiment-app-chart.fullname" . }}-app
  subsets:
    - name: v1
      labels: { version: v1 }
    - name: v2
      labels: { version: v2 }
{{- end }}