apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
    name: {{ include "sentiment-app-chart.fullname" . }}-gateway
    namespace: {{ include "sentiment-app-chart.namespace" . }}
spec:
    selector: { istio: ingressgateway }
    servers:
    - port: { number: 80, name: http, protocol: HTTP }
        hosts: [ "*" ]