{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gmail-smtp-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  appPassword: "{{ .Values.emailPassword }}"
{{- end }}