{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-gmail-smtp-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  appPassword: "{{ .Values.emailPassword }}"
{{- end }}