{{- if (not .Values.istioEnabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-ingress
spec:
  ingressClassName: nginx 
  rules:
    - host: {{ printf "%s%s" .Release.Name .Values.app.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sentiment-app-chart.fullname" . }}-app
                port:
                  number: {{ .Values.app.ingress.servicePort }}
{{- end }}