apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-service-v1
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
    version: v1
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ include "sentiment-app-chart.fullname" . }}-model-service
      {{- include "sentiment-app-chart.selectorLabels" . | nindent 6 }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "sentiment-app-chart.fullname" . }}-model-service
        {{- include "sentiment-app-chart.selectorLabels" . | nindent 8 }}
        version: v1
    spec:
      containers:
        - name: {{ include "sentiment-app-chart.fullname" . }}-model-service
          image: "{{ .Values.modelService.image }}:{{ .Values.modelService.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-model-env
          volumeMounts:
            - name: model-cache
              mountPath: /app/model-cache
            - name: cv-cache
              mountPath: /app/cv-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-model-cache
        - name: cv-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-cv-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-service-v2
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
    version: v2
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ include "sentiment-app-chart.fullname" . }}-model-service
      {{- include "sentiment-app-chart.selectorLabels" . | nindent 6 }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ include "sentiment-app-chart.fullname" . }}-model-service
        {{- include "sentiment-app-chart.selectorLabels" . | nindent 8 }}
        version: v2
    spec:
      containers:
        - name: {{ include "sentiment-app-chart.fullname" . }}-model-service
          image: "{{ .Values.modelService.image }}:{{ .Values.modelService.tagv2 }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-model-env
          volumeMounts:
            - name: model-cache
              mountPath: /app/model-cache
            - name: cv-cache
              mountPath: /app/cv-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-model-cache
        - name: cv-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-cv-cache