{{- if .Values.istioEnabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: { name: {{ include "sentiment-app-chart.fullname" . }}-model-service-virtualservice }
spec:
    hosts: [ {{ include "sentiment-app-chart.fullname" . }}-model-service ]
    http:
    - match:
      - sourceLabels: { version: v2 }
      route:
      - destination: { host: {{ include "sentiment-app-chart.fullname" . }}-model-service, subset: v2 }
    - route:
      - destination: { host: {{ include "sentiment-app-chart.fullname" . }}-model-service, subset: v1 }
{{- end }}