apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: "{{ .Values.modelService.image }}:{{ .Values.modelService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.modelService.port }}
          envFrom:
            - configMapRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-model-env
          volumeMounts:
            - name: model-cache
              mountPath: /app/model-cache
            - name: cv-cache
              mountPath: /app/cv-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-model-cache
        - name: cv-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-cv-cache