apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-env
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
data:
  CV_CACHE_DIR: ./cv-cache
  CV_URL: https://github.com/remla25-team5/model-training/releases/download/{MODEL_VERSION}/c1_BoW_Sentiment_Model.pkl
  MODEL_CACHE_DIR: ./model-cache
  MODEL_URL: https://github.com/remla25-team5/model-training/releases/download/{MODEL_VERSION}/c2_Classifier_Sentiment_Model.joblib
  MODEL_VERSION: 0.0.1
  MODEL_SERVICE_HOST: "0.0.0.0"
  MODEL_SERVICE_PORT: "5000"