apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-service
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ include "sentiment-app-chart.fullname" . }}-model-service
      {{- include "sentiment-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "sentiment-app-chart.fullname" . }}-model-service
        {{- include "sentiment-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "sentiment-app-chart.fullname" . }}-model-service
          image: "{{ .Values.modelService.image }}:{{ .Values.modelService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.modelService.port }}
          envFrom:
            - configMapRef:
                name: {{ include "sentiment-app-chart.fullname" . }}-model-env
          volumeMounts:
            - name: model-cache
              mountPath: /app/model-cache
            - name: cv-cache
              mountPath: /app/cv-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-model-cache
        - name: cv-cache
          persistentVolumeClaim:
            claimName: {{ include "sentiment-app-chart.fullname" . }}-cv-cache