apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: model
