apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model
spec:
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: model
