apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model-cache
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeSize }}