apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-model
  labels:
    {{- include "sentiment-app-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  selector:
    app: model
    {{- include "sentiment-app-chart.selectorLabels" . | nindent 4 }}
