{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app-rules
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
  - name: {{ include "sentiment-app-chart.name" . }}.rules
    rules:
    - alert: RapidSubmissionIncrease
      expr: rate(total_submissions_total[60s]) > 0.25
      for: 2m
      annotations:
        title: 'the service receives more than 15 submissions per minute for two minutes straight'
        description: 'the service receives more than 15 submissions per minute for two minutes straight'
      labels:
        severity: warning
        app: {{ include "sentiment-app-chart.name" . }}
        namespace: 'default'
{{- end }}