{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-app-rules
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
  - name: {{ include "sentiment-app-chart.name" . }}.rules
    rules:
    - alert: RapidSubmissionIncrease
      expr: rate(total_submissions_total[60s]) > 0.25
      for: 2m
      annotations:
        title: 'the service receives more than 15 submissions per minute for two minutes straight'
        description: 'the service receives more than 15 submissions per minute for two minutes straight'
      labels:
        severity: warning
        app: {{ include "sentiment-app-chart.name" . }}
        namespace: 'default'
  - name: model_quality
  # Test Monitor 7: the model has not experienced a regression in prediction quality on served data
    rules:
      - alert: ModelPredictionErrorRateHigh
        expr: verification_error_rate_last_week > 0.2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Model prediction error rate is above 20% in the last week"
{{- end }}