{{- if .Values.istioEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-ratelimit-config 
data:
  config.yaml: |
    domain: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
    descriptors:
      - key: PATH
        value: "api"
        descriptors:
          - key: x-user
            rate_limit:
              unit: minute
              requests_per_unit: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-redis 
  labels:
    app: {{ include "sentiment-app-chart.fullname" . }}-redis  (Labels must be unique too)
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: {{ include "sentiment-app-chart.fullname" . }}-redis 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-redis 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-app-chart.fullname" . }}-redis 
  template:
    metadata:
      labels:
        app: {{ include "sentiment-app-chart.fullname" . }}-redis 
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
  labels:
    app: {{ include "sentiment-app-chart.fullname" . }}-ratelimit
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-debug
    port: 6070
    targetPort: 6070
    protocol: TCP
  selector:
    app: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
      annotations:
        proxy.istio.io/config: |-
          proxyStatsMatcher:
            inclusionRegexps:
            - ".*http_local_rate_limit.*"
    spec:
      containers:
      - image: envoyproxy/ratelimit:30a4ce1a
        imagePullPolicy: IfNotPresent
        name: ratelimit
        command: ["/bin/ratelimit"]
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: "{{ include "sentiment-app-chart.fullname" . }}-redis:6379"
        - name: USE_STATSD
          value: "false"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: HOST
          value: "::"
        - name: GRPC_HOST
          value: "::"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 6070
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sentiment-app-chart.fullname" . }}-ratelimit-config
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-filter-ratelimit 
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: {{ include "sentiment-app-chart.fullname" . }}-ratelimit 
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||{{ include "sentiment-app-chart.fullname" . }}-ratelimit.{{ .Release.Namespace }}.svc.cluster.local
                  authority: {{ include "sentiment-app-chart.fullname" . }}-ratelimit.{{ .Release.Namespace }}.svc.cluster.local
              transport_api_version: V3
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-filter-ratelimit-svc-api 
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "{{ printf "%s-%s" .Release.Name .Values.app.ingress.host }}:80"
            route:
              name: "api"
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
            - actions:
              - header_value_match:
                  descriptor_key: "PATH"
                  descriptor_value: "api"
                  headers:
                    - name: ":path"
                      safe_regex_match:
                        google_re2: {}
                        regex: "/api/submit"
              - request_headers:
                  header_name: "x-user"
                  descriptor_key: "x-user"
{{- end }}