{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sentiment-app-chart.fullname" . }}-service-monitor
  labels:
    release: sentiment-app
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      {{- include "sentiment-app-chart.labels" . | nindent 4 }}
{{- end }}