# general.yaml
---
- hosts: all
  become: yes
  vars:
    node_count: "{{ node_count | default(2) }}"
    ctrl_cpus: "{{ ctrl_cpus | default(1) }}"
    ctrl_memory: "{{ ctrl_memory | default(4096) }}"
    node_cpus: "{{ node_cpus | default(2) }}"
    node_memory: "{{ node_memory | default(6144) }}"
  tasks:
    # Step 4
    - name: Authorize SSH keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_items:
        - "../ssh-keys/id_ed25519_jorn.pub"
        - "../ssh-keys/id_ed25519_kevin.pub"
        - "../ssh-keys/id_ed25519_kristof.pub"
        - "../ssh-keys/id_ed25519_reinier.pub"
        - "../ssh-keys/id_ed25519_tadas.pub"

    # Step 5
    - name: Disable swap for the running system
      shell: swapoff -a

    - name: Remove swap entry in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent
      
     # Test step 
    - name: Print configuration info
      debug:
        msg: "Node count: {{ node_count }}, Controller CPUs: {{ ctrl_cpus }}, Controller Memory: {{ ctrl_memory }}MB, Node CPUs: {{ node_cpus }}, Node Memory: {{ node_memory }}MB"
