# general.yaml
---
- hosts: all
  become: yes
  vars:
    node_count: "{{ node_count | default(2) }}"
    ctrl_cpus: "{{ ctrl_cpus | default(1) }}"
    ctrl_memory: "{{ ctrl_memory | default(4096) }}"
    node_cpus: "{{ node_cpus | default(2) }}"
    node_memory: "{{ node_memory | default(6144) }}"
  tasks:
    # Step 4
    - name: Authorize SSH keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_items:
        - "../ssh-keys/id_ed25519_jorn.pub"
        - "../ssh-keys/id_ed25519_kevin.pub"
        - "../ssh-keys/id_ed25519_kristof.pub"
        - "../ssh-keys/id_ed25519_reinier.pub"
        - "../ssh-keys/id_ed25519_tadas.pub"

    # Step 5
    - name: Disable swap for the running system
      shell: swapoff -a

    - name: Remove swap entry in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent

     # Test step 
    - name: Print configuration info
      debug:
        msg: "Node count: {{ node_count }}, Controller CPUs: {{ ctrl_cpus }}, Controller Memory: {{ ctrl_memory }}MB, Node CPUs: {{ node_cpus }}, Node Memory: {{ node_memory }}MB"

    - name: br_netfilter
      ansible.builtin.copy:
        content: 'overlay br_netfilter'
        dest: /etc/modules-load.d/k8s.conf

    - name: Add the br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present

    # Set ip forwarding on in /proc and verify token value with the sysctl command
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true

    - ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_set: true

    - ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        sysctl_set: true

    - name: Add mappings to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      loop:
        - { name: ctrl, ip: 192.168.56.100 }
        - { name: node-1, ip: 192.168.56.101 }
        - { name: node-2, ip: 192.168.56.102 }

    - name: Add kubernetes repository
      block:
        - name: somerepo |no apt key
          ansible.builtin.get_url:
            url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
            dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

        - name: somerepo | apt source
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
            state: present

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes

    - name: Install the version '1.7.24' of package "containerd"
      ansible.builtin.apt:
        name: containerd=1.7.24*

    - name: Install the version '1.1.12' of package "runc"
      ansible.builtin.apt:
        name: runc=1.1.12*

    - name: Install the version '1.32.4' of package "kubeadm"
      ansible.builtin.apt:
        name: kubeadm=1.32.4*

    - name: Install the version '1.32.4' of package "kubelet"
      ansible.builtin.apt:
        name: kubelet=1.32.4*

    - name: Install the version '1.32.4' of package "kubectl"
      ansible.builtin.apt:
        name: kubectl=1.32.4*
# Step 11
    - name: Ensure /etc/containerd directory exists
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'
      become: true

    - name: Dump containerd default config if missing
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml
      become: true

    - name: Wait for /etc/containerd/config.toml to be created
      wait_for:
        path: /etc/containerd/config.toml
        state: present   # Corrected state
        timeout: 30      # Wait up to 30 seconds for the file to exist
      become: true

    - name: Disable AppArmor in containerd config
      lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '^\[plugins\."io.containerd.grpc.v1.cri"\]'
        regexp: '^\s*disable_apparmor\s*='
        line: '  disable_apparmor = true'
      become: true

    - name: Set sandbox image version in containerd config
      lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '^\[plugins\."io.containerd.grpc.v1.cri"\]'
        regexp: '^\s*sandbox_image\s*='
        line: '  sandbox_image = "registry.k8s.io/pause:3.10"'
      become: true

    - name: Enable SystemdCgroup in containerd config
      lineinfile:
        path: /etc/containerd/config.toml
        insertafter: '^\[plugins\."io.containerd.grpc.v1.cri"\.containerd\.runtimes\.runc\.options\]'
        regexp: '^\s*SystemdCgroup\s*='
        line: '  SystemdCgroup = true'
      become: true

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: true
      become: true

# Step 12
    - name: Enable and start kubelet service
      service:
        name: kubelet
        state: started
        enabled: true
      become: true

