# node.yaml
---
- hosts: nodes
  become: yes
  # Pass variables from Vagrant to Ansible
  vars:
    node_count: "{{ node_count | default(2) }}"
    node_id: "{{ node_id | default(0) }}"
    ctrl_cpus: "{{ ctrl_cpus | default(1) }}"
    ctrl_memory: "{{ ctrl_memory | default(4096) }}"
    node_cpus: "{{ node_cpus | default(2) }}"
    node_memory: "{{ node_memory | default(6144) }}"
  tasks:
  # Test step
    - name: Print worker node configuration
      debug:
        msg: "Worker node {{ node_id }} of {{ node_count }} with {{ node_cpus }} CPUs and {{ node_memory }}MB memory"

    # Check if worker node has already joined the cluster
    - name: Check if Kubernetes is already initialized (kubelet.conf exists)
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubeadm_config

    # Step 18: Generate Join Command for Worker Nodes
    - name: "Generate join command for worker nodes"
      command: kubeadm token create --print-join-command
      register: join_command
      when: not kubeadm_config.stat.exists
      delegate_to: ctrl
      run_once: true

    # Step 19: Run Join Command on Worker Nodes
    # run the captured command on the worker nodes
    - name: "Run join command on worker nodes"
      ansible.builtin.shell: "{{ join_command.stdout }}"
      when: not kubeadm_config.stat.exists
      register: join_result
      become: true
