# node.yaml
---
- hosts: nodes
  become: yes
  # Pass variables from Vagrant to Ansible
  vars:
    node_count: "{{ node_count | default(2) }}"
    node_id: "{{ node_id | default(0) }}"
    ctrl_cpus: "{{ ctrl_cpus | default(1) }}"
    ctrl_memory: "{{ ctrl_memory | default(4096) }}"
    node_cpus: "{{ node_cpus | default(2) }}"
    node_memory: "{{ node_memory | default(6144) }}"
  tasks:
  # Test step
    - name: Print worker node configuration
      debug:
        msg: "Worker node {{ node_id }} of {{ node_count }} with {{ node_cpus }} CPUs and {{ node_memory }}MB memory"
